#spring:
 # datasource:
  #  url: jdbc:postgresql://localhost:5432/database_name
    #username: postgres
    #password: tiger
    #driver-class-name: org.postgresql.Driver
  #jpa:
   # hibernate:
    #  ddl-auto: create
    #show-sql: true
    #properties:
     # hibernate:
      #  format_sql: true
    #database: postgresql
    #atabase-platform: org.hibernate.dialect.PostgreSQLDialect